### ISSUE TITLE
Accounts out of sync

### ISSUE THREAD

**Issue by wbconnor** [voraciousdev/octo#8]
Mobile is chrome pinned to home screen (PWA) on Pixel 2 XL

Desktop is FireFox on Mac

Notice there is no `#employee_emergency` note in the desktop version. 

![image](https://user-images.githubusercontent.com/8883983/89599092-87feba00-d82c-11ea-85ad-9e7e72edecf8.png)

![Screen Shot 2020-08-06 at 9 31 19 PM (2)](https://user-images.githubusercontent.com/8883983/89599154-b8465880-d82c-11ea-8b78-1a08718f4119.png)

**Comment by wbconnor** [comment]
I might have fat-fingered the `discard` button. Maybe this card should be to request moving the discard button or adding a verification question.

**Comment by wbconnor** [comment]
Nope. It's still out of sync even after restoring the note on mobile.

![Screen Shot 2020-08-06 at 9 40 17 PM (2)](https://user-images.githubusercontent.com/8883983/89599399-7669e200-d82d-11ea-864a-0f0e496c84fe.png)

**Comment by wbconnor** [comment]
It didn't show up till I edited and saved a note on desktop.

**Comment by voraciousdev** [comment]
> Maybe this card should be to request moving the discard button or adding a verification question.

I purposely decided against a verification prompt when discarding, because the document can be restored by navigating to the `discarded` filter and clicking `restore`.

> It didn't show up till I edited and saved a note on desktop.

Do you know whether or not the page was already open on desktop? Currently, the app only attempts a sync on initial page load (opening the app) and on mutable operations. If the page was already open on desktop, that would explain why the sync didn't happen until you performed a mutable operation (editing a note).

Either way, I would like to trigger a sync on more operations (like opening a list view). I will label this as an enhancement for now, but if you have more information, I might change it to a bug.

**Comment by voraciousdev** [comment]
It looks like I need to listen to the `SET_USER` action in `plugins/sync.js`.

**Comment by austenmadden** [comment]
I had this issue arise when testing. I tend to hop back and forth between desktop and mobile.
